### ISSUE TITLE
Noctis frame data has a few fields missing

### ISSUE THREAD

**Issue by bdickason** [harounb/tekken-frame-data#11]
I noticed a few inconsistencies with the Noctis frame data in `t7/t7-noctis-1.json`:

1. d/f+4, 2 has a null 'on ch' field and no notes field
2. WS+1 is missing on_block, on_hit, on_ch, and notes fields and the 'speed' field is likely the 'on_block' data
3. WS+3,2 is missing on_block, on_hit, on_ch, and notes fields and the 'speed' field includes the words throw (I don't think this is a throw)

Also a small one: d/f+1, 4 says "Tail Spion" in the notes instead of "Tail Spin"

**Comment by harounb** [comment]
Hi!
I've corrected 1 by downloading the latest frame data. You can see someone reported that:
http://rbnorway.org/noctis-t7-frames/#comment-12613
Unfortunately the other issues are with the source data at rbnorway. 
I will raise it with Madcow he should fix it promptly.

Thanks for reporting!

Edit:

I've requested for them to fix here:
http://rbnorway.org/noctis-t7-frames/#comment-12620 
However it will probably still say throw due to the animation that occurs upon hit. (similar to 2,2,b+2)
